services:
  postgres:
    image: postgres
    container_name: postgres-urls
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5050:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: