env: "local"
  
postgres:
  driver:     "postgres"
  host:       "localhost"
  port:       5050
  username:   "postgres"
  password:   "mysecretpassword"
  sslmode:       "disable"
  db_name:           "postgres"
  max_open_conns: 25
  max_idle_conns: 25
  max_idle_time:  1m

server_url_shortener:
  host:         "localhost"
  port:         7777
  timeout:      4s
  idle_timeout: 30s
  id_api:       2